### ISSUE TITLE
Should Mithril be a regular dependency?

### ISSUE THREAD

**Issue by tivac** [StephanHoyer/mithril-node-render#2]
Shouldn't it be a regular dependency instead of a devdependency? I don't know that this package makes much sense without also having mithril installed. You'd also then be explicitly tying it to a mithril version, which would be good in case mithril changes the underlying format of the data structure returned by `m()`, thus breaking this module.

I can send a PR your way if you agree, it's a pretty small change ;)

**Comment by StephanHoyer** [comment]
I don't think this should be a regular dependency, because you don't really need mithril to use this module. The virtual DOM the module consumes can be produced by any other system as well. This is currently not the case but may be in the future.

Also if you declare this as a subdependency, the module loader in you app will not find it, since it always walks upwards the directory tree, never downwards.

Or am I wrong here?

**Comment by tivac** [comment]
Oh, duh. I guess a peerDependency would be a bit closer but those have their own problems. Ignore me!

**Comment by StephanHoyer** [comment]
ok,

no problem :)
